# Autogenerated wrapper script for GRASS_jll for x86_64-linux-gnu-cxx03
export libgrass_arraystats, libgrass_bitmap, libgrass_btree, libgrass_btree2, libgrass_cairodriver, libgrass_calc, libgrass_ccmath, libgrass_cdhc, libgrass_cluster, libgrass_datetime, libgrass_dbmibase, libgrass_dbmiclient, libgrass_dbmidriver, libgrass_dbstubs, libgrass_dgl, libgrass_dig2, libgrass_display, libgrass_driver, libgrass_dspf, libgrass_g3d, libgrass_gis, libgrass_gmath, libgrass_gpde, libgrass_gproj, libgrass_htmldriver, libgrass_imagery, libgrass_interpdata, libgrass_interpfl, libgrass_iortho, libgrass_lidar, libgrass_linkm, libgrass_lrs, libgrass_manage, libgrass_neta, libgrass_pngdriver, libgrass_psdriver, libgrass_qtree, libgrass_raster, libgrass_rli, libgrass_rowio, libgrass_rtree, libgrass_segment, libgrass_shape, libgrass_sim, libgrass_sqlp, libgrass_stats, libgrass_symb, libgrass_temporal, libgrass_vector, libgrass_vedit

using GDAL_jll
using PROJ_jll
using Cairo_jll
using FreeType2_jll
using LAPACK_jll
using FFTW_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("GRASS")
JLLWrappers.@declare_library_product(libgrass_arraystats, "libgrass_arraystats.7.8.so")
JLLWrappers.@declare_library_product(libgrass_bitmap, "libgrass_bitmap.7.8.so")
JLLWrappers.@declare_library_product(libgrass_btree, "libgrass_btree.7.8.so")
JLLWrappers.@declare_library_product(libgrass_btree2, "libgrass_btree2.7.8.so")
JLLWrappers.@declare_library_product(libgrass_cairodriver, "libgrass_cairodriver.7.8.so")
JLLWrappers.@declare_library_product(libgrass_calc, "libgrass_calc.7.8.so")
JLLWrappers.@declare_library_product(libgrass_ccmath, "libgrass_ccmath.7.8.so")
JLLWrappers.@declare_library_product(libgrass_cdhc, "libgrass_cdhc.7.8.so")
JLLWrappers.@declare_library_product(libgrass_cluster, "libgrass_cluster.7.8.so")
JLLWrappers.@declare_library_product(libgrass_datetime, "libgrass_datetime.7.8.so")
JLLWrappers.@declare_library_product(libgrass_dbmibase, "libgrass_dbmibase.7.8.so")
JLLWrappers.@declare_library_product(libgrass_dbmiclient, "libgrass_dbmiclient.7.8.so")
JLLWrappers.@declare_library_product(libgrass_dbmidriver, "libgrass_dbmidriver.7.8.so")
JLLWrappers.@declare_library_product(libgrass_dbstubs, "libgrass_dbstubs.7.8.so")
JLLWrappers.@declare_library_product(libgrass_dgl, "libgrass_dgl.7.8.so")
JLLWrappers.@declare_library_product(libgrass_dig2, "libgrass_dig2.7.8.so")
JLLWrappers.@declare_library_product(libgrass_display, "libgrass_display.7.8.so")
JLLWrappers.@declare_library_product(libgrass_driver, "libgrass_driver.7.8.so")
JLLWrappers.@declare_library_product(libgrass_dspf, "libgrass_dspf.7.8.so")
JLLWrappers.@declare_library_product(libgrass_g3d, "libgrass_g3d.7.8.so")
JLLWrappers.@declare_library_product(libgrass_gis, "libgrass_gis.7.8.so")
JLLWrappers.@declare_library_product(libgrass_gmath, "libgrass_gmath.7.8.so")
JLLWrappers.@declare_library_product(libgrass_gpde, "libgrass_gpde.7.8.so")
JLLWrappers.@declare_library_product(libgrass_gproj, "libgrass_gproj.7.8.so")
JLLWrappers.@declare_library_product(libgrass_htmldriver, "libgrass_htmldriver.7.8.so")
JLLWrappers.@declare_library_product(libgrass_imagery, "libgrass_imagery.7.8.so")
JLLWrappers.@declare_library_product(libgrass_interpdata, "libgrass_interpdata.7.8.so")
JLLWrappers.@declare_library_product(libgrass_interpfl, "libgrass_interpfl.7.8.so")
JLLWrappers.@declare_library_product(libgrass_iortho, "libgrass_iortho.7.8.so")
JLLWrappers.@declare_library_product(libgrass_lidar, "libgrass_lidar.7.8.so")
JLLWrappers.@declare_library_product(libgrass_linkm, "libgrass_linkm.7.8.so")
JLLWrappers.@declare_library_product(libgrass_lrs, "libgrass_lrs.7.8.so")
JLLWrappers.@declare_library_product(libgrass_manage, "libgrass_manage.7.8.so")
JLLWrappers.@declare_library_product(libgrass_neta, "libgrass_neta.7.8.so")
JLLWrappers.@declare_library_product(libgrass_pngdriver, "libgrass_pngdriver.7.8.so")
JLLWrappers.@declare_library_product(libgrass_psdriver, "libgrass_psdriver.7.8.so")
JLLWrappers.@declare_library_product(libgrass_qtree, "libgrass_qtree.7.8.so")
JLLWrappers.@declare_library_product(libgrass_raster, "libgrass_raster.7.8.so")
JLLWrappers.@declare_library_product(libgrass_rli, "libgrass_rli.7.8.so")
JLLWrappers.@declare_library_product(libgrass_rowio, "libgrass_rowio.7.8.so")
JLLWrappers.@declare_library_product(libgrass_rtree, "libgrass_rtree.7.8.so")
JLLWrappers.@declare_library_product(libgrass_segment, "libgrass_segment.7.8.so")
JLLWrappers.@declare_library_product(libgrass_shape, "libgrass_shape.7.8.so")
JLLWrappers.@declare_library_product(libgrass_sim, "libgrass_sim.7.8.so")
JLLWrappers.@declare_library_product(libgrass_sqlp, "libgrass_sqlp.7.8.so")
JLLWrappers.@declare_library_product(libgrass_stats, "libgrass_stats.7.8.so")
JLLWrappers.@declare_library_product(libgrass_symb, "libgrass_symb.7.8.so")
JLLWrappers.@declare_library_product(libgrass_temporal, "libgrass_temporal.7.8.so")
JLLWrappers.@declare_library_product(libgrass_vector, "libgrass_vector.7.8.so")
JLLWrappers.@declare_library_product(libgrass_vedit, "libgrass_vedit.7.8.so")
function __init__()
    JLLWrappers.@generate_init_header(GDAL_jll, PROJ_jll, Cairo_jll, FreeType2_jll, LAPACK_jll, FFTW_jll, Libiconv_jll)
    JLLWrappers.@init_library_product(
        libgrass_arraystats,
        "lib/libgrass_arraystats.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_bitmap,
        "lib/libgrass_bitmap.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_btree,
        "lib/libgrass_btree.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_btree2,
        "lib/libgrass_btree2.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_cairodriver,
        "lib/libgrass_cairodriver.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_calc,
        "lib/libgrass_calc.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_ccmath,
        "lib/libgrass_ccmath.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_cdhc,
        "lib/libgrass_cdhc.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_cluster,
        "lib/libgrass_cluster.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_datetime,
        "lib/libgrass_datetime.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbmibase,
        "lib/libgrass_dbmibase.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbmiclient,
        "lib/libgrass_dbmiclient.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbmidriver,
        "lib/libgrass_dbmidriver.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbstubs,
        "lib/libgrass_dbstubs.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dgl,
        "lib/libgrass_dgl.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dig2,
        "lib/libgrass_dig2.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_display,
        "lib/libgrass_display.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_driver,
        "lib/libgrass_driver.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dspf,
        "lib/libgrass_dspf.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_g3d,
        "lib/libgrass_g3d.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gis,
        "lib/libgrass_gis.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gmath,
        "lib/libgrass_gmath.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gpde,
        "lib/libgrass_gpde.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gproj,
        "lib/libgrass_gproj.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_htmldriver,
        "lib/libgrass_htmldriver.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_imagery,
        "lib/libgrass_imagery.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_interpdata,
        "lib/libgrass_interpdata.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_interpfl,
        "lib/libgrass_interpfl.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_iortho,
        "lib/libgrass_iortho.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_lidar,
        "lib/libgrass_lidar.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_linkm,
        "lib/libgrass_linkm.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_lrs,
        "lib/libgrass_lrs.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_manage,
        "lib/libgrass_manage.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_neta,
        "lib/libgrass_neta.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_pngdriver,
        "lib/libgrass_pngdriver.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_psdriver,
        "lib/libgrass_psdriver.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_qtree,
        "lib/libgrass_qtree.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_raster,
        "lib/libgrass_raster.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_rli,
        "lib/libgrass_rli.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_rowio,
        "lib/libgrass_rowio.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_rtree,
        "lib/libgrass_rtree.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_segment,
        "lib/libgrass_segment.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_shape,
        "lib/libgrass_shape.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_sim,
        "lib/libgrass_sim.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_sqlp,
        "lib/libgrass_sqlp.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_stats,
        "lib/libgrass_stats.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_symb,
        "lib/libgrass_symb.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_temporal,
        "lib/libgrass_temporal.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_vector,
        "lib/libgrass_vector.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_vedit,
        "lib/libgrass_vedit.7.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
