# Autogenerated wrapper script for GRASS_jll for x86_64-apple-darwin
export libgrass_arraystats, libgrass_bitmap, libgrass_btree, libgrass_btree2, libgrass_cairodriver, libgrass_calc, libgrass_ccmath, libgrass_cdhc, libgrass_cluster, libgrass_datetime, libgrass_dbmibase, libgrass_dbmiclient, libgrass_dbmidriver, libgrass_dbstubs, libgrass_dgl, libgrass_dig2, libgrass_display, libgrass_driver, libgrass_dspf, libgrass_g3d, libgrass_gis, libgrass_gmath, libgrass_gpde, libgrass_gproj, libgrass_htmldriver, libgrass_imagery, libgrass_interpdata, libgrass_interpfl, libgrass_iortho, libgrass_lidar, libgrass_linkm, libgrass_lrs, libgrass_manage, libgrass_neta, libgrass_pngdriver, libgrass_psdriver, libgrass_qtree, libgrass_raster, libgrass_rli, libgrass_rowio, libgrass_rtree, libgrass_segment, libgrass_shape, libgrass_sim, libgrass_sqlp, libgrass_stats, libgrass_symb, libgrass_temporal, libgrass_vector, libgrass_vedit

using GDAL_jll
using PROJ_jll
using Cairo_jll
using FreeType2_jll
using LAPACK_jll
using FFTW_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("GRASS")
JLLWrappers.@declare_library_product(libgrass_arraystats, "@rpath/libgrass_arraystats.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_bitmap, "@rpath/libgrass_bitmap.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_btree, "@rpath/libgrass_btree.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_btree2, "@rpath/libgrass_btree2.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_cairodriver, "@rpath/libgrass_cairodriver.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_calc, "@rpath/libgrass_calc.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_ccmath, "@rpath/libgrass_ccmath.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_cdhc, "@rpath/libgrass_cdhc.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_cluster, "@rpath/libgrass_cluster.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_datetime, "@rpath/libgrass_datetime.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_dbmibase, "@rpath/libgrass_dbmibase.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_dbmiclient, "@rpath/libgrass_dbmiclient.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_dbmidriver, "@rpath/libgrass_dbmidriver.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_dbstubs, "@rpath/libgrass_dbstubs.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_dgl, "@rpath/libgrass_dgl.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_dig2, "@rpath/libgrass_dig2.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_display, "@rpath/libgrass_display.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_driver, "@rpath/libgrass_driver.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_dspf, "@rpath/libgrass_dspf.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_g3d, "@rpath/libgrass_g3d.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_gis, "@rpath/libgrass_gis.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_gmath, "@rpath/libgrass_gmath.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_gpde, "@rpath/libgrass_gpde.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_gproj, "@rpath/libgrass_gproj.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_htmldriver, "@rpath/libgrass_htmldriver.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_imagery, "@rpath/libgrass_imagery.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_interpdata, "@rpath/libgrass_interpdata.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_interpfl, "@rpath/libgrass_interpfl.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_iortho, "@rpath/libgrass_iortho.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_lidar, "@rpath/libgrass_lidar.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_linkm, "@rpath/libgrass_linkm.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_lrs, "@rpath/libgrass_lrs.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_manage, "@rpath/libgrass_manage.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_neta, "@rpath/libgrass_neta.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_pngdriver, "@rpath/libgrass_pngdriver.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_psdriver, "@rpath/libgrass_psdriver.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_qtree, "@rpath/libgrass_qtree.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_raster, "@rpath/libgrass_raster.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_rli, "@rpath/libgrass_rli.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_rowio, "@rpath/libgrass_rowio.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_rtree, "@rpath/libgrass_rtree.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_segment, "@rpath/libgrass_segment.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_shape, "@rpath/libgrass_shape.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_sim, "@rpath/libgrass_sim.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_sqlp, "@rpath/libgrass_sqlp.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_stats, "@rpath/libgrass_stats.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_symb, "@rpath/libgrass_symb.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_temporal, "@rpath/libgrass_temporal.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_vector, "@rpath/libgrass_vector.7.8.dylib")
JLLWrappers.@declare_library_product(libgrass_vedit, "@rpath/libgrass_vedit.7.8.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GDAL_jll, PROJ_jll, Cairo_jll, FreeType2_jll, LAPACK_jll, FFTW_jll, Libiconv_jll)
    JLLWrappers.@init_library_product(
        libgrass_arraystats,
        "lib/libgrass_arraystats.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_bitmap,
        "lib/libgrass_bitmap.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_btree,
        "lib/libgrass_btree.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_btree2,
        "lib/libgrass_btree2.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_cairodriver,
        "lib/libgrass_cairodriver.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_calc,
        "lib/libgrass_calc.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_ccmath,
        "lib/libgrass_ccmath.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_cdhc,
        "lib/libgrass_cdhc.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_cluster,
        "lib/libgrass_cluster.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_datetime,
        "lib/libgrass_datetime.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbmibase,
        "lib/libgrass_dbmibase.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbmiclient,
        "lib/libgrass_dbmiclient.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbmidriver,
        "lib/libgrass_dbmidriver.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dbstubs,
        "lib/libgrass_dbstubs.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dgl,
        "lib/libgrass_dgl.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dig2,
        "lib/libgrass_dig2.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_display,
        "lib/libgrass_display.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_driver,
        "lib/libgrass_driver.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_dspf,
        "lib/libgrass_dspf.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_g3d,
        "lib/libgrass_g3d.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gis,
        "lib/libgrass_gis.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gmath,
        "lib/libgrass_gmath.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gpde,
        "lib/libgrass_gpde.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_gproj,
        "lib/libgrass_gproj.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_htmldriver,
        "lib/libgrass_htmldriver.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_imagery,
        "lib/libgrass_imagery.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_interpdata,
        "lib/libgrass_interpdata.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_interpfl,
        "lib/libgrass_interpfl.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_iortho,
        "lib/libgrass_iortho.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_lidar,
        "lib/libgrass_lidar.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_linkm,
        "lib/libgrass_linkm.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_lrs,
        "lib/libgrass_lrs.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_manage,
        "lib/libgrass_manage.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_neta,
        "lib/libgrass_neta.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_pngdriver,
        "lib/libgrass_pngdriver.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_psdriver,
        "lib/libgrass_psdriver.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_qtree,
        "lib/libgrass_qtree.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_raster,
        "lib/libgrass_raster.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_rli,
        "lib/libgrass_rli.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_rowio,
        "lib/libgrass_rowio.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_rtree,
        "lib/libgrass_rtree.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_segment,
        "lib/libgrass_segment.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_shape,
        "lib/libgrass_shape.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_sim,
        "lib/libgrass_sim.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_sqlp,
        "lib/libgrass_sqlp.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_stats,
        "lib/libgrass_stats.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_symb,
        "lib/libgrass_symb.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_temporal,
        "lib/libgrass_temporal.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_vector,
        "lib/libgrass_vector.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrass_vedit,
        "lib/libgrass_vedit.7.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
